version: '3'
services:
  db:
    image: nouchka/sqlite3
    container_name: sqlite-container
    volumes:
      - ./bd:/bd
    ports:
      - "5000:5000"
    environment:
      - DB_PATH=/bd/bd.sql
    command: tail -f /dev/null

  backend:
    build: ./serveur
    container_name: backend-container
    ports:
      - "5001:5000"
    volumes:
      - ./serveur:/app
    environment:
      - DATABASE_URL=sqlite:/bd/bd.sql
    depends_on:
      - db
    command: npm run dev

  frontend:
    build: ./client  # Le chemin du répertoire contenant le Dockerfile pour le frontend
    container_name: frontend-container
    ports:
      - "3000:80"  # Exposer le port 3000 sur ton hôte et mapper avec le port 80 du conteneur
    depends_on:
      - backend
